trigger:
- qa

pool:
  vmImage: ubuntu-latest

variables:
  - group: vg-fe-qa

stages:
- stage: Build
  displayName: 'Build Application'
  jobs:
  - job: BuildApp
    displayName: 'Build and Package Application'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '22.x'
      displayName: 'Step 1: Install Node.js'

    - script: |
        echo "NEXT_PUBLIC_BASE_URL=$(NEXT_PUBLIC_BASE_URL)"
        npm install --legacy-peer-deps
        npm run build
      displayName: 'Step 2: npm install and build'

    - script: |
        mkdir -p build/standalone/build
        mv ./build/static ./build/standalone/build
        mv ./public ./build/standalone
      displayName: 'Step 3: Prepare build structure'

    - script: |
        sudo apt-get update && sudo apt-get install -y zip
      displayName: 'Step 4: Install zip utility'

    - script: |
        zip -r app-$(Build.BuildId).zip build/standalone -x "*.git*" "azure-pipelines.yml"
        ls -lah
      displayName: 'Step 5: Create deployment package'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(System.DefaultWorkingDirectory)/app-$(Build.BuildId).zip'
        artifactName: 'build-artifact'
        publishLocation: 'Container'
      displayName: 'Step 6: Publish build artifacts'

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployToAzure
    displayName: 'Deploy to Azure Web App'
    environment: 'fe-qa'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Starting Deployment Step"
              echo "Listing downloaded artifacts:"
              ls -lah $(Pipeline.Workspace)/build-artifact/
            displayName: 'Step 1: Pre-deployment verification'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'frontend-service-connection'
              appType: 'webAppLinux'
              appName: 'app-fe-eqsdbacalc-qa'
              package: '$(Pipeline.Workspace)/build-artifact/app-$(Build.BuildId).zip'
              runtimeStack: 'NODE|22-lts'
              deploymentMethod: 'zipDeploy'
            displayName: 'Step 2: Deploy to Azure Web App'